name: feels_golden
description: Common patterns for screenshot-based widget testing using Goldens. Forked from the eBay's flutter_glove_box repository.
version: 0.16.9
homepage: https://github.com/Dinip/feels_golden/
repository: https://github.com/Dinip/feels_golden/
issue_tracker: https://github.com/Dinip/feels_golden/issues
# Original repository (now abandoned): https://github.com/eBay/flutter_glove_box/

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.15.0

dev_dependencies:
  flutter_lints: ^5.0.0
  test_api: ^0.7.0

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: packages/feels_golden/fonts/Roboto-Regular.ttf
